theme = "iroaseta"

[editor]
middle-click-paste = false
bufferline = "always"
color-modes = true
true-color = true
undercurl = true
[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
[editor.whitespace.render]
space = "none"
nbsp = "all"
nnbsp = "all"
tab = "all"
newline = "none"
tabpad = "none"
[editor.indent-guides]
render = true

[keys.insert.j]
j = "normal_mode"
k = "normal_mode"

[keys.normal]
H = ":buffer-previous"
L = ":buffer-next"

[keys.normal.space]
w = ":write"
W = ":write-all"
f = "file_picker"
F = "file_picker_in_current_directory"
"." = "file_picker_in_current_buffer_directory"
x = ":buffer-close"
X = ":buffer-close!"
o = ":buffer-close-others"
O = ":buffer-close-others!"
q = ":quit"
Q = ":quit!"
"space" = "command_mode"
