[[language]]
name = "cpp"
formatter = { command = 'clang-format' }
auto-format = true

[[language]]
name = "rust"
formatter = { command = 'rustfmt', args = ['+nightly'] }

[[language]]
name = "toml"
formatter = { command = 'taplo', args = ['fmt', '-'] }
auto-format = true
