# `sheldon` configuration file
# ----------------------------

shell = "zsh"

[plugins.compinit]
inline = 'autoload -Uz compinit && compinit'

[plugins.colors]
inline = 'autoload -Uz colors && colors'

[plugins.starship]
inline = 'eval "$(starship init zsh)"'

[plugins.zoxide]
inline = 'eval "$(zoxide init zsh)"'

[plugins.mise]
inline = 'eval "$(mise activate zsh)"'

[plugins.mcfly]
inline = 'eval "$(mcfly init zsh)"'

[plugins.zsh-autosuggestions]
github = 'zsh-users/zsh-autosuggestions'

[plugins.zsh-syntax-highlighting]
github = 'zsh-users/zsh-syntax-highlighting'

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"


